import { assets } from "../assets/assets";

export const brandsData = [
  {
    id: "BRD001",
    name: "Bosch Tools",
    logo: assets.brand,
    metadata: "Leading German manufacturer known for durable and precision-engineered power tools.",
    foundedYear: 1886,
    originCountry: "Germany",
    speciality: "Power Tools, Accessories, Measuring Tools",
    isFeatured: true,
  },
  {
    id: "BRD002",
    name: "DeWalt",
    logo: assets.brand,
    metadata: "Trusted American brand offering rugged and reliable tools for professionals.",
    foundedYear: 1924,
    originCountry: "USA",
    speciality: "Construction Tools, Cordless Systems",
    isFeatured: true,
  },
  {
    id: "BRD003",
    name: "Makita",
    logo: assets.brand,
    metadata: "Japanese innovation leader in battery-powered and electric tools.",
    foundedYear: 1915,
    originCountry: "Japan",
    speciality: "Cordless Tools, Industrial Tools",
  },
  {
    id: "BRD004",
    name: "Hitachi Power Tools",
    logo: assets.brand,
    metadata: "High-quality Japanese tools focused on precision and durability.",
    foundedYear: 1910,
    originCountry: "Japan",
    speciality: "Heavy Machinery, Cutting & Drilling Tools",
  },
  {
    id: "BRD005",
    name: "Black+Decker",
    logo: assets.brand,
    metadata: "Popular consumer brand offering efficient home and DIY tools.",
    foundedYear: 1910,
    originCountry: "USA",
    speciality: "DIY Tools, Household Appliances",
  },
  {
    id: "BRD006",
    name: "Stanley",
    logo: assets.brand,
    metadata: "Iconic brand with a legacy of durable hand tools and precision instruments.",
    foundedYear: 1843,
    originCountry: "USA",
    speciality: "Hand Tools, Measuring Instruments",
  },
  {
    id: "BRD007",
    name: "Hilti",
    logo: assets.brand,
    metadata: "Premium European brand specializing in professional construction tools.",
    foundedYear: 1941,
    originCountry: "Liechtenstein",
    speciality: "Drilling, Anchoring, Fastening Systems",
  },
  {
    id: "BRD008",
    name: "Craftsman",
    logo: assets.brand,
    metadata: "American classic known for strong warranty-backed tools and outdoor equipment.",
    foundedYear: 1927,
    originCountry: "USA",
    speciality: "Automotive Tools, Outdoor Equipment",
  },
  {
    id: "BRD009",
    name: "Metabo",
    logo: assets.brand,
    metadata: "German manufacturer recognized for innovative cordless tool systems.",
    foundedYear: 1924,
    originCountry: "Germany",
    speciality: "Cordless Tools, Metalworking Equipment",
  },
  {
    id: "BRD010",
    name: "Karcher",
    logo: assets.brand,
    metadata: "Global leader in cleaning systems and pressure washers for industrial use.",
    foundedYear: 1935,
    originCountry: "Germany",
    speciality: "Cleaning Systems, Pressure Washers",
  },
];
