import { assets } from "../assets/assets";

export const products =[
  {
    "id": 1,
    "name": "Bosch GSB 501 Professional Impact Drill",
    "brand": "Bosch",
    "category": "Power Tools",
    "price": 2999,
    "rating": 4.6,
    "stock": 35,
    "warranty": "6 months",
    "image":assets.tools,
    "delivery": "2-4 days",
    "reviewsCount": 420,
    "description": "High-speed 500W impact drill with forward/reverse function — ideal for metal, wood & masonry."
  },
  {
    "id": 2,
    "name": "Stanley STHT46008 Claw Hammer 16oz",
    "brand": "Stanley",
    "category": "Hand Tools",
    "price": 899,
    "rating": 4.4,
    "stock": 70,
    "warranty": "1 year",
    "image":assets.tools,
    "delivery": "3-5 days",
    "reviewsCount": 280,
    "description": "Durable steel hammer with anti-slip grip and magnetic nail starter — perfect for home or site use."
  },
  {
    "id": 3,
    "name": "Black+Decker KC4815 Cordless Screwdriver Kit",
    "brand": "Black+Decker",
    "category": "Cordless Tools",
    "price": 2499,
    "rating": 4.2,
    "stock": 42,
    "warranty": "1 year",
    "image":assets.tools,
    "delivery": "2-3 days",
    "reviewsCount": 360,
    "description": "Rechargeable screwdriver kit with 15 bits and LED light — compact, easy to carry, and powerful."
  },
  {
    "id": 4,
    "name": "Makita 9553NB Angle Grinder 100mm",
    "brand": "Makita",
    "category": "Grinders",
    "price": 4299,
    "rating": 4.7,
    "stock": 18,
    "warranty": "6 months",
    "image":assets.tools,
    "delivery": "1-3 days",
    "reviewsCount": 220,
    "description": "Powerful 710W motor with high heat resistance — lightweight and ergonomic for professional use."
  },
  {
    "id": 5,
    "name": "Taparia 1408 Combination Plier 8-inch",
    "brand": "Taparia",
    "category": "Hand Tools",
    "price": 375,
    "rating": 4.5,
    "stock": 150,
    "warranty": "Lifetime",
    "image":assets.tools,
    "delivery": "3-6 days",
    "reviewsCount": 520,
    "description": "Drop-forged, fully insulated combination plier with precision grip and rust-resistant coating."
  },
  {
    "id": 6,
    "name": "Bosch GWS 600 Professional Angle Grinder",
    "brand": "Bosch",
    "category": "Grinders",
    "price": 3599,
    "rating": 4.6,
    "stock": 22,
    "warranty": "1 year",
    "image":assets.tools,
    "delivery": "2-4 days",
    "reviewsCount": 410,
    "description": "600W motor, spindle lock for easy disc change, compact & efficient performance for daily use."
  },
  {
    "id": 7,
    "name": "3M Safety Goggles Anti-Fog Protection",
    "brand": "3M",
    "category": "Safety Equipment",
    "price": 599,
    "rating": 4.3,
    "stock": 80,
    "warranty": "No warranty",
    "image":assets.tools,
    "delivery": "4-6 days",
    "reviewsCount": 190,
    "description": "Lightweight polycarbonate goggles with anti-fog lens and splash protection for workshops."
  },
  {
    "id": 8,
    "name": "Karcher K2 Compact Pressure Washer",
    "brand": "Karcher",
    "category": "Cleaning Tools",
    "price": 9999,
    "rating": 4.5,
    "stock": 12,
    "warranty": "1 year",
    "image":assets.tools,
    "delivery": "2-5 days",
    "reviewsCount": 160,
    "description": "Compact 1400W pressure washer ideal for car cleaning and outdoor surfaces — German engineered."
  },
  {
    "id": 9,
    "name": "Dewalt D25133K Rotary Hammer Drill 800W",
    "brand": "DeWalt",
    "category": "Power Tools",
    "price": 7299,
    "rating": 4.8,
    "stock": 15,
    "warranty": "1 year",
    "image":assets.tools,
    "delivery": "1-3 days",
    "reviewsCount": 240,
    "description": "Heavy-duty 3-mode rotary hammer ideal for drilling in concrete, metal, and wood."
  },
  {
    "id": 10,
    "name": "JCB Hand Tool Kit (39 Pieces)",
    "brand": "JCB",
    "category": "Tool Kits",
    "price": 2299,
    "rating": 4.4,
    "stock": 55,
    "warranty": "6 months",
    "image":assets.tools,
    "delivery": "2-4 days",
    "reviewsCount": 310,
    "description": "39-piece professional toolkit for household and mechanical work — durable case and grip design."
  }
]
